"""add addresses table

Revision ID: 938a2330f7d3
Revises: 
Create Date: 2025-12-28 23:23:50.605891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938a2330f7d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=16), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=20), nullable=True),
    sa.Column('accuracy', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Longitud (coordenada X)'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Latitud (coordenada Y)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_addresses_city', 'addresses', ['city'], unique=False)
    op.create_index('idx_addresses_coords', 'addresses', ['longitude', 'latitude'], unique=False)
    op.create_index('idx_addresses_full', 'addresses', ['city', 'street', 'number'], unique=False)
    op.create_index('idx_addresses_region', 'addresses', ['region'], unique=False)
    op.create_index('idx_addresses_street', 'addresses', ['street'], unique=False)
    op.create_index(op.f('ix_addresses_hash'), 'addresses', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_hash'), table_name='addresses')
    op.drop_index('idx_addresses_street', table_name='addresses')
    op.drop_index('idx_addresses_region', table_name='addresses')
    op.drop_index('idx_addresses_full', table_name='addresses')
    op.drop_index('idx_addresses_coords', table_name='addresses')
    op.drop_index('idx_addresses_city', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
